server:
  runMode: "debug"  #debug or release
  httpPort: 8080

mysql:
  user: "admin"
  password: "admin"
  host: "127.0.0.1"
  port: 3306
  database: "gin-test"
  charset: "utf8"

redis:
  password: "admin"
  host: "127.0.0.1"
  port: 6379